
trigger:
  - main
pool:
  vmImage: 'ubuntu-latest'
stages:
  - stage: BuildApp
    jobs:
      - job: BuildPushImage
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'dockerhub'
              repository: 'dockerhubusername/dockerhubrepo'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
              tags: 'latest'
